# Generated by Django 4.2.2 on 2023-07-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DespensaFabi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('enlatados', 'Enlatados'), ('bebidas', 'Bebidas'), ('jugos', 'Jugos'), ('limpieza', 'Limpieza'), ('comestibles', 'Comestibles'), ('lacteos', 'Lacteos'), ('cocina', 'Cocina'), ('fiambres', 'Fiambres'), ('mayoreo', 'Mayoreo')], default='comestibles', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
