# Generated by Django 4.2.2 on 2023-07-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DespensaFabi', '0002_producto_categoria_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('enlatados', 'Enlatados'), ('bebidas', 'Bebidas'), ('jugos', 'Jugos'), ('limpieza', 'Limpieza'), ('comestibles', 'Comestibles'), ('lacteos', 'Lacteos'), ('cocina', 'Cocina'), ('fiambres', 'Fiambres'), ('mayoreo', 'Mayoreo'), ('otros', 'Otros')], default='comestibles', max_length=20),
        ),
    ]
